<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.26">
  <POU Name="fb_ratio_trimming" Id="{d3cfa3b6-537a-4da3-a8d7-0f48afbd3e17}">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_ratio_trimming

VAR_INPUT
	loop14: REAL;
	loop15: REAL;
END_VAR

VAR_OUTPUT
	r1: REAL;
	r4: REAL;
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
r1 := loop14 + r1;
r4 := loop15 - loop14 + r4;
]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>