<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.26">
  <POU Name="fb_xmeas_acquire" Id="{cd0e3f91-bbf0-4630-b6d2-13bb1b3d09c9}">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_xmeas_acquire

VAR_INPUT
END_VAR

VAR_OUTPUT
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>