<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.26">
  <POU Name="fb_ratio_trimming" Id="{c85cb863-192a-49b2-aaa4-aafda1e75c5c}">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_ratio_trimming

VAR_INPUT
END_VAR

VAR_OUTPUT
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>