%reads in all the .dat files from temain_(w/e).exe output

[infor, err, msg] = stat("localchanges.txt");

if (err == -1)
temp = [];
save -ascii localchanges.txt temp;
[infor, err, msg] = stat("localchanges.txt");
end

flag = infor.size;

%for convenience: delete these file because they are generated by the fortran programs, but not used.
delete("TE_data_inc.dat");
delete("TE_data_me01.dat");

if (flag != 0) %i.e. it has some data in it already

initial = load("localchanges.txt");
[r, c] = size(initial);
delete("localchanges.txt");

array = reader();

%append the data from local changes to the back of array
for i=1:1:c
array(:,1+i) = initial(:,i);
end

save -ascii localchanges.txt array

else

array = reader();

save -ascii localchanges.txt array

end


